tasks:
  - init: go install github.com/matryer/moq@latest
  - init: brew install httpie
  - init: brew install bat
  - init: alias cat=bat
  - init: cd 04-simple-mock-gen && go install && cd ..
vscode:
  extensions:
    - golang.go
    - https://github.com/jinliming2/vscode-go-template/releases/download/v0.2.1/vscode-go-template-0.2.1.vsix
    - eamodio.gitlens
