// Code generated by simple-mock-gen; DO NOT EDIT.

package main

import "context"

type AirplaneStorerMock struct {
	AirplaneFunc  func(ctx context.Context, id int64) (string, error)
	AirplanesFunc func(ctx context.Context) ([]string, error)
}

func (mock *AirplaneStorerMock) Airplane(ctx context.Context, id int64) (string, error) {
	return mock.AirplaneFunc(ctx, id)
}

func (mock *AirplaneStorerMock) Airplanes(ctx context.Context) ([]string, error) {
	return mock.AirplanesFunc(ctx)
}
